apiVersion: v1
kind: Service
metadata:
  name: car-svc
  namespace: car
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    madeby: uct
  type: LoadBalancer